import React from "react";
import * as Icon from "react-feather";
import { Permission } from "../components/Webase/functions";
const { can } = Permission;
const navigationConfig = [
  {
    id: "dash",
    title: "Main",
    type: "item",
    icon: <Icon.Home size={20} />,
    navLink: "/dashboard",
    visible: false,
  },
  // {
  //   id: "News",
  //   title: "Main",
  //   type: "item",
  //   icon: <Icon.Home size={20} />,
  //   navLink: "/dashboard",
  //   visible: ["NewsView"],
  // },
  {
    type: "groupHeader",
    groupTitle: "Management",
  },
  {
    id: "Administration",
    title: "Administration",
    type: "collapse",
    icon: <Icon.Users size={20} />,
    children: [
      {
        id: "Employee",
        title: "Employee",
        type: "item",
        icon: <Icon.User size={20} />,
        navLink: "/info/employee",
        visible: ["EmployeeView", "BranchesEmployeeView", "AllEmployeeView"],
      },
      {
        id: "Kadr",
        title: "Kadr",
        type: "item",
        icon: <Icon.User size={20} />,
        navLink: "/info/kadr",
        visible: ["BranchesEmployeeView", "AllEmployeeView"],
      },
      {
        id: "User",
        title: "User",
        type: "item",
        icon: <Icon.User size={20} />,
        navLink: "/management/user",
        visible: ["UserView", "BranchesUserView", "AllUserView"],
      },
      {
        id: "Position",
        title: "Positions",
        type: "item",
        icon: <Icon.Layers size={20} />,
        navLink: "/info/position",
        visible: ["PositionView", "AllPositionView"],
      },
      {
        id: "Role",
        title: "Role",
        type: "item",
        icon: <Icon.Cast size={20} />,
        navLink: "/management/role",
        visible: ["RoleView"],
      },
      {
        id: "EmployeeAttestation",
        title: "EmployeeAttestation",
        type: "item",
        icon: <Icon.Calendar size={20} />,
        navLink: "/document/employeeattestation",
        visible: ["EmployeeWithAttestationView"],
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Document",
  },
  {
    id: "Checks",
    title: "Checks",
    type: "collapse",
    icon: <Icon.CheckSquare size={20} />,
    children: [
      {
        id: "Request",
        title: "Request",
        type: "item",
        icon: <Icon.Layers size={20} />,
        navLink: "/document/request",
        visible: [
          "RequestView",
          "BranchesRequestView",
          "AllRequestView",
          "RequestReceive",
          "AllRequestReceive",
          "RequestAgree",
          "AllRequestAgree",
        ],
        // badge: true,
        // badgeText: "5",
      },
      {
        id: "Postponement",
        title: "RequestPostponement",
        type: "item",
        icon: <Icon.Layers size={20} />,
        navLink: "/document/postponement",
        visible: [
          "RequestView",
          "BranchesRequestView",
          "AllRequestView",
          "RequestReceive",
          "AllRequestReceive",
          "RequestAgree",
          "AllRequestAgree",
        ],
        // badge: true,
        // badgeText: "4",
      },
      {
        id: "InspectionConclusion",
        title: "InspectionConclusion",
        type: "item",
        icon: <Icon.Layers size={20} />,
        navLink: "/document/inspectionconclusion",
        visible: [
          "InspectionConclusionView",
          // "BranchesRequestView",
          // "AllRequestView",
          // "RequestReceive",
          // "AllRequestReceive",
          // "RequestAgree",
          // "AllRequestAgree",
        ],
      },
      {
        id: "InspectionResult",
        title: "InspectionResult",
        type: "item",
        icon: <Icon.Layers size={20} />,
        navLink: "/document/inspectionresult",
        visible: [
          "RequestView",
          "BranchesRequestView",
          "AllRequestView",
          "RequestReceive",
          "AllRequestReceive",
          // "RequestAgree",
          // "AllRequestAgree",
        ],
        // badge: true,
        // badgeText: "3",
      },
      // {
      //   id: "InspectionBook",
      //   title: "InspectionBook",
      //   type: "item",
      //   icon: <Icon.Layers size={20} />,
      //   navLink: "/document/inspectionbook",
      //   visible: [
      //     "RequestView",
      //     "BranchesRequestView",
      //     "AllRequestView",
      //     "RequestReceive",
      //     "AllRequestReceive",
      //     // "RequestAgree",
      //     // "AllRequestAgree",
      //   ],
      //   // badge: true,
      //   // badgeText: "4",
      // },
      {
        id: "Complaint",
        title: "Complaint",
        type: "item",
        icon: <Icon.FolderPlus size={20} />,
        navLink: "/document/complaint",
        visible: [
          "RequestReceive",
          "AllRequestReceive",
          // "RequestAgree",
          // "AllRequestAgree",
        ],
      },
      {
        id: "InspectionBookOfContractor",
        title: "InspectionBookOfContractor",
        type: "item",
        icon: <Icon.FolderPlus size={20} />,
        navLink: "/document/inspectionbookofcontractor",
        visible: [
          "RequestReceive",
          "AllRequestReceive",
          // "RequestAgree",
          // "AllRequestAgree",
        ],
      },
    ],
  },
  {
    id: "Attestation",
    title: "Attestation",
    type: "item",
    icon: <Icon.Calendar size={20} />,
    navLink: "/document/attestation",
    visible: [
      "AttestationView",
      "BranchesAttestationView",
      "AllAttestationView",
      "AttestationHeld",
    ],
  },
  {
    id: "Videolesson",
    title: "Videolesson",
    type: "item",
    icon: <Icon.Film size={20} />,
    navLink: "/document/videolesson",
    visible: ["VideoLessonView"],
  },
  {
    id: "VideolessonView",
    title: "VideolessonView",
    type: "item",
    icon: <Icon.Video size={20} />,
    navLink: "/document/videolessonview",
    visible: ["VideoLessonView"],
  },

  {
    type: "groupHeader",
    groupTitle: "Info",
  },
  {
    id: "GlobalDirectory",
    title: "GlobalDirectory",
    type: "collapse",
    icon: <Icon.Database size={20} />,
    children: [
      {
        id: "Organization",
        title: "organizationSidebar",
        type: "item",
        icon: <Icon.Grid size={20} />,
        navLink: "/management/organization",
        visible: ["OrganizationView", "AllOrganizationView"],
      },
      {
        id: "Contractor",
        title: "Contractor",
        type: "item",
        icon: <Icon.FolderPlus size={20} />,
        navLink: "/document/contractor",
        visible: ["ContractorView"],
      },
      {
        id: "Country",
        title: "Country",
        type: "item",
        icon: <Icon.Circle size={20} />,
        navLink: "/info/country",
        visible: ["CountryView"],
      },
      {
        id: "Region",
        title: "Region",
        type: "item",
        icon: <Icon.Circle size={20} />,
        navLink: "/info/region",
        visible: ["RegionView"],
      },
      {
        id: "District",
        title: "District",
        type: "item",
        icon: <Icon.Circle size={20} />,
        navLink: "/info/district",
        visible: ["DistrictView"],
      },
      {
        id: "Nationality",
        title: "Nationality",
        type: "item",
        icon: <Icon.User size={20} />,
        navLink: "/info/nationality",
        visible: ["CitizenshipView"],
      },
      {
        id: "Citizenship",
        title: "Citizenship",
        type: "item",
        icon: <Icon.UserCheck size={20} />,
        navLink: "/info/citizenship",
        visible: ["CitizenshipView"],
      },
      {
        id: "CheckBasis",
        title: "CheckBasis",
        type: "item",
        icon: <Icon.CheckCircle size={20} />,
        navLink: "/info/checkbasis",
        visible: ["CheckBasisView"],
      },
      {
        id: "Oked",
        title: "Oked",
        type: "item",
        icon: <Icon.File size={20} />,
        navLink: "/info/oked",
        visible: ["OkedView"],
      },
      {
        id: "Bank",
        title: "Bank",
        type: "item",
        icon: <Icon.DollarSign size={20} />,
        navLink: "/info/bank",
        visible: ["BankView"],
      },
      {
        id: "ControlFunctionForm",
        title: "ControlFunctionForm",
        type: "item",
        icon: <Icon.Globe size={25} />,
        navLink: "/info/controlfunctionform",
        visible: ["ControlFunctionFormView"],
      },
      {
        id: "OrganFunction",
        title: "OrganFunction",
        type: "item",
        icon: <Icon.Codepen size={20} />,
        navLink: "/info/organfunction",
        visible: "OrganFunctionView",
      },
      {
        id: "CheckingQuiz",
        title: "CheckingQuiz",
        type: "item",
        icon: <Icon.Box size={20} />,
        navLink: "/info/checkingquiz",
        visible: ["CheckingQuizView", "AllCheckingQuizView"],
      },
    ],
  },

  // {
  //   id: "OrderType",
  //   title: "OrderType",
  //   type: "item",
  //   icon: <Icon.Layers size={20} />,
  //   navLink: "/info/ordertype",
  //   visible: "OrderTypeView",
  // },

  {
    id: "OrganizationDirectory",
    title: "OrganizationDirectory",
    type: "collapse",
    icon: <Icon.Copy size={20} />,
    children: [
      {
        id: "ControlFunction",
        title: "ControlFunction",
        type: "item",
        icon: <Icon.Globe size={20} />,
        navLink: "/info/controlfunction",
        visible: ["ControlFunctionView", "AllControlFunctionView"],
      },
      {
        id: "Videocategory",
        title: "Videocategory",
        type: "item",
        icon: <Icon.Video size={20} />,
        navLink: "/info/videocategory",
        visible: ["VideoCategoryView"],
      },

      // {
      //   id: "PositionClassifier",
      //   title: "PositionClassifier",
      //   type: "item",
      //   icon: <Icon.Layers size={25} />,
      //   navLink: "/info/positionclassifier",
      //   visible: ["PositionClassifierView"],
      // },
      {
        id: "MandatoryRequirement",
        title: "MandatoryRequirement",
        type: "item",
        icon: <Icon.AlertOctagon size={25} />,
        navLink: "/info/mandatoryrequirement",
        visible: ["MandatoryRequirementView", "AllMandatoryRequirementView"],
      },
      {
        id: "RejectionReason",
        title: "RejectionReason",
        type: "item",
        icon: <Icon.ExternalLink size={22} />,
        navLink: "/info/rejectionreason",
        visible: ["RejectionReasonView"],
      },
      {
        id: "OrganizationInspectionType",
        title: "OrganizationInspectionType",
        type: "item",
        icon: <Icon.Circle size={25} />,
        navLink: "/info/organizationinspectiontype",
        visible: ["OrganizationInspectionTypeView"],
      },
    ],
  },
  {
    id: "News",
    title: "News",
    type: "item",
    icon: <Icon.Folder size={20} />,
    navLink: "/info/news",
    visible: ["NewsView"],
  },
  {
    type: "groupHeader",
    groupTitle: "Reports",
  },
  {
    id: "ExcelDirectory",
    title: "ExcelDirectory",
    type: "collapse",
    icon: <Icon.Copy size={20} />,
    children: [
      {
        id: "ExcelReport",
        title: "ExcelReport",
        type: "item",
        icon: <Icon.Folder size={20} />,
        navLink: "/info/excelreport",
        visible: ["Report1View"],
      },
      {
        id: "ExcelReport2",
        title: "ExcelReport2",
        type: "item",
        icon: <Icon.Folder size={20} />,
        navLink: "/info/excelreport2",
        visible: ["Report2View"],
      },
      {
        id: "ExcelReport3",
        title: "ExcelReport3",
        type: "item",
        icon: <Icon.Folder size={20} />,
        navLink: "/info/excelreport3",
        visible: ["Report3View"],
      },
      {
        id: "ExcelReport4",
        title: "ExcelReport4",
        type: "item",
        icon: <Icon.Folder size={20} />,
        navLink: "/info/excelreport4",
        visible: ["Report4View"],
      },
      {
        id: "ExcelReport5",
        title: "ExcelReport5",
        type: "item",
        icon: <Icon.Folder size={20} />,
        navLink: "/info/excelreport5",
        visible: ["Report5View"],
      },
    ],
  },
];

export default navigationConfig;
